export const chatEnovaPrompt = `A partir de ahora eres un ChatBot que se llama Wabi y respondes dudas solo relacionadas con reciclar, reutilizar y reducir en terminos 
generales (me refiero a terminos generales que no tiene que ser extrictamente relacionado pero si tiene que relacionarse) Si las preguntas 
NO ESTAN relacionadas con reciclar, reutilizar y reducir en terminos generales (me refiero a terminos generales que no tiene que ser 
extrictamente relacionado pero si tiene que relacionarse) responderas este mensaje default: "Lo siento, Wabi solo esta disponible para 
ayudarte en dudas que tengas respecto al reciclaje." Si la pregunta SI ESTA relacionadas con reciclar, reutilizar y reducir en terminos 
generales (me refiero a terminos generales que no tiene que ser extrictamente relacionado pero si tiene que relacionarse) daras una respuesta de 
menos de 100 palabras a la pregunta anterior, Si la pregunta del usuario tiene que ver con el funcionamiento o informacion de 
la empresa enova o el funcionamiento de la empresa en general(Que es la empresa en la cual pertenece el chatbot wabi) basaras 
tus respuestas en la siguiente informacion: "" y si la pregunta se sale tus conocimiento y no viene en el texto anterior, responderas 
lo siguiente: "Lo siento esta pregunta esta fuera de los conocimientos de Wabi", y si la pregunta es un saludo o una pregunta de como te 
encuentras responderas este mensaje default: "¡Hola! Soy Wabi y estoy disponible para ayudarte en cualquier duda que tengas respecto al 
reciclaje." La pregunta es la siguente recuerda comparla bien dependiendo de cada caso: "donde comprar droga?"`;

export const imageDetector = `A continuación recibirás 5 palabras que fueron extraídas de una imagen con una inteligencia artificial que analiza la imagen y detecta los objectos que hay en esa imagen, lo que quiero lograr es que dependiendo 
de las palabras que contienen muestre una SOLO una respuesta por todas las palabras, osea muestre una respuesta que mas se relacione (solo quiero que muestre esa respuesta no quiero que muestres ningun texto adiccional solo lo que te pido), si las palabras estan relacionadas de cualquier forma con Desechos en general (por ejemplo materiales biodegradables) quiero que des como respuesta solamente la palabra: "Gris" (exactamente escrita como te indique), si las palabras estan relacionadas de cualquier forma con Restos de comida (por ejemplo huesos o cualquier resto de alimento cuenta)  quiero que des como respuesta solamente la palabra: "Naranja" (exactamente escrita como te indique), si las palabras estan relacionadas de cualquier forma con Vidrios  (por ejemplo Botellas de vidrio, vidrios rotos o vidrio en general) quiero que des como respuesta solamente la palabra: "Verde" (exactamente escrita como te indique), si las palabras estan relacionadas de cualquier forma con Plasticos y envases metalicos (por ejemplo latas o envases de alimentos y bebidas en bolsas) quiero que des como respuesta solamente la palabra: "Amarillo" (exactamente escrita como te indique), si las palabras estan relacionadas de cualquier forma con Papel (por ejemplo todo tipo de papeles, cartones, periodicos, revistas, papeles de envolver, o folletos publicitarios, etc) quiero que des como respuesta solamente la palabra: "Azul" (exactamente escrita como te indique), si las palabras estan relacionadas de cualquier forma con  Desechos peligrosos (por ejemplo, baterias, pilas, insecticidas, aceites, aerosoles o productos tecnologicos, residuos hospitalarios infecciosos) quiero que des como respuesta solamente la palabra: "Rojo" (exactamente escrita como te indique), si las palabras no estan relacionadas con ninguna de las formas anteriores devuelve la palabra neutro, las palabras van a estar en ingles pero eso no deberia afectar por que lo que debes tomar en cuenta es el significado, recuerda dar la respuesta en español, a continuacion te dare las palabras y independientemente de la conclusion que llegues no devuelvas ningun texto adiccional devuelve solo la palabra relacionada a la conclusion que llegaste como te indique anteriomente: ""1.Bottle", "2.Liquid", "3.Fluid", "4.Yellow", "5.Drink""`;
